# Node.js with React

# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest
steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo a >> 1.js
      echo b >> 2.js

- task: DeleteFiles@1
  inputs:
    SourceFolder: 
    Contents: |
      !**/1.js
      (**/*.js)


- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      ls