# Node.js with React

# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: Default

steps:
- task: SSHptytest3@0
  inputs:
    sshEndpoint: 'SSH test connection - local agent (user1)'
    runOptions: 'commands'
    interactiveSession: true
    commands: |
      sudo echo aa
      sudo -su crm
    readyTimeout: '20000'