# Node.js with React

# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: Default

steps:
- task: InstallSSHKeytest@0
  inputs:
    knownHostsEntry: 'sss'
    sshPublicKey: 'ss'
    sshPassphrase: 'ss'
    sshKeySecureFile: 'sss'

    
- task: InstallSSHKeytest@0
  inputs:
    knownHostsEntry: 'sss'
    sshPublicKey: 'ss'
    sshPassphrase: 'ss'
    sshKeySecureFile: 'sss'

    
- task: InstallSSHKeytest@0
  inputs:
    knownHostsEntry: 'sss'
    sshPublicKey: 'ss'
    sshPassphrase: 'ss'
    sshKeySecureFile: 'sss'