# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: 'Default'

steps:
- task: SSHPtyTest@0
  inputs:
    sshEndpoint: 'SSH test connection - local agent'
    runOptions: 'inline'
    inline: 'cd /data && mkdir aaa'
    readyTimeout: '20000'