# Node.js with React

# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
variables:
  secureFileName: "secureFile.txt"
pool:
  vmImage: windows-latest

stages:
- stage: stage
  jobs:
  - job: job
    steps:
      - task: DownloadSecureFile@1
        inputs:
          secureFile: $(secureFileName)
      - task: CmdLine@2
        inputs:
          script: |
            cd $(Agent.TempDirectory)
            dir